name: Build AutoClicker Driver
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install latest SDK and WDK available via choco
      - name: Install SDK and WDK
        run: |
          choco install windows-sdk-11 -y
          choco install windows-driver-kit -y

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # Build project ignoring version warnings
      - name: Build Driver
        run: |
          msbuild AutoClicker.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTargetPlatformVersion=10.0

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-Build
          path: |
            **/*.sys
            **/*.exe
